import type { Metadata } from "next";
import { Inter } from "next/font/google";
import AuthSession from "@/app/_component/AuthSession";
import "./globals.css";
import { MSWComponent } from "@/app/_component/MSWComponent";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className} suppressHydrationWarning={true}>
        <MSWComponent />
        <AuthSession>{children}</AuthSession>
      </body>
    </html>
  );
}
